version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-auth.sql:/docker-entrypoint-initdb.d/init-auth.sql
      - ./init-account.sql:/docker-entrypoint-initdb.d/init-account.sql
      - ./init-transfer.sql:/docker-entrypoint-initdb.d/init-transfer.sql
      - ./init-currency.sql:/docker-entrypoint-initdb.d/init-currency.sql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

#  config-server:
#    build: ./config-server
#    container_name: config-server
#    ports:
#      - "8888:8888"
#    depends_on:
#      - postgres
#
#  service-discovery:
#    build: ./service-discovery
#    container_name: service-discovery
#    ports:
#      - "8761:8761"

volumes:
  pgdata: