server:
  port: 8083

spring:
  application:
    name: ms-currency

  datasource:
    url: jdbc:postgresql://postgres:5432/currency_db
    username: postgres
    password: postgres

  data:
    redis:
      url: redis://redis:6379  # Docker-da Redis servisinə qoşulmaq üçün

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka
