server:
  port: 8084

spring:
  application:
    name: ms-transfer
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka